#
# List of emails to send report and deposit notifications. Can also set
# "from" field in emails.
#
# Emails for local environments.
# Emails are not actually sent in local environments, therefore the emails don't
# have to be valid.
local: &local
  mail_deliverer: ac@columbia.edu
  administrative_notifications: example@columbia.edu
  error_notifications: developers@library.columbia.edu

development: *local
test: *local


# Emails for deployed dev/test environments.
deployed: &deployed
  mail_deliverer: ac@columbia.edu
  administrative_notifications:
    - ac@columbia.edu
    - cmg2228@columbia.edu
  error_notifications: cmg2228@columbia.edu

academiccommons_dev: *deployed
academiccommons_test: *deployed
academiccommons_prod: *deployed
ac4_dev: *deployed
ac4_test: *deployed

academiccommons_prod:
  mail_deliverer: ac@columbia.edu
  administrative_notifications: ac@columbia.edu
  error_notifications: diag@library.columbia.edu
