version: "3.9"

# Although a name isn't required for docker to work, we want to explicitly specify it so we know
# which prefix is used for the volumes that we create.
name: 'ac-test'

volumes:
  solr-cores:
  fedora-data:
services:
  solr:
    build: ./solr
    restart: always
    ports:
      - '9983:8983'
    environment:
      # In a Docker environment we enable the analysis-extras module via SOLR_OPTS, but in a production
      # environment we're more likely to set `SOLR_MODULES=analysis-extras` in solr.in.sh.
      - SOLR_OPTS=-Dsolr.modules=analysis-extras
    volumes:
      - solr-cores:/data
  fedora:
    build: ./fedora
    restart: always
    ports:
      - '9080:8080'
    volumes:
      - fedora-data:/opt/fedora/data
